apiVersion: v1
kind: Service
metadata:
  name: foo
  labels:
    app: foo
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    nodePort: 30080
    targetPort: 8080
  selector:
    app: foo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: foo-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: foo
        version: v1
    spec:
      containers:
      - name: foo
        image: neighbor/foo:latest
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: neighborsecret
